### ISSUE TITLE
Git repository name fix

### ISSUE THREAD

**Issue by mudrd8mz** [grabs/moodle-tool_userdebug#1]
As per https://docs.moodle.org/dev/Plugin_contribution_checklist#Code_repository_name it would be best to rename the name of this repository so that it reads "moodle-tool_userdebug" (not "tools").

Note that Github transparently forwards the requests to the old URL to the new ones after rename so there should be no problem with that. 

https://docs.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by grabs** [comment]
Thank you!
I renamed the repository and changed the url in the moodle plugin database.
Best regards!
