### ISSUE TITLE
"Ad hoc debug (off)" link shows up on the home page

### ISSUE THREAD

**Issue by golenkovm** [grabs/moodle-tool_userdebug#14]
Please see screenshots below.

Student view of the home page:
![image](https://github.com/user-attachments/assets/76a7f60b-b841-4baa-bc22-8c10728cb57d)

Admin view:
![image](https://github.com/user-attachments/assets/4f453e91-4f30-4470-9f5a-aa074e098b6b)

 Admin view on another site:
![image](https://github.com/user-attachments/assets/82b443a3-63c1-4291-85e0-8edfbb5f1937)

It would be good to be able to remove it from the home page

**Comment by grabs** [comment]
Hi,
it seems that you have given the user the capability “tool/userdebug:adhocdebug”. Without this capability a user should not see this link at all (except the site admin).

**Comment by golenkovm** [comment]
Hi @grabs thanks for taking a look. I guess that's the way it was installed (with the defaults) but we'll double check that.

Here is what role permissions we have defined (all `Not set`):
![image](https://github.com/user-attachments/assets/d31e22fb-5aca-45e9-bc14-410956527288)

**Comment by grabs** [comment]
That looks correct to me. 
What versions of Moodle and tool_userdebug are you using exactly?

**Comment by golenkovm** [comment]
One site is Moodle 4.1.14+ Build: 20241018 with tool_userdebug v4.4 (2024050900). Another one that I checked is Moodle 4.1.14 Build: 20241007 with the same version of tool_userdebug v4.4 (2024050900).

I've just installed the latest version of the plugin to a completely fresh 4.1 vanilla Moodle site and it behaves the same way.

Home page as an admin:
![image](https://github.com/user-attachments/assets/e0d485ec-60e7-4810-accd-86a75b641280)

As a student:
![image](https://github.com/user-attachments/assets/a2a511b3-ea16-4c58-8fb6-c79ac10f94f5)

And it installs the same way in Moodle 4.3.

I hope this helps.

**Comment by grabs** [comment]
I am sorry, but I really can't reproduce this at all. There must be some specialty on your system which gives a user the capability to use this tool.
What happens if the user click on this link? Can he do this without an error?

**Comment by golenkovm** [comment]
Yes, the link is operational and the user increases their debugging level.

**Comment by grabs** [comment]
Can it be you are trying the user account not with a real login but with "Login as"?
This would explain it.
If you switch the account by using "Login as" you'll keep the capability to use the tool.
Please try a real login and check whether the plugin works correctly.

**Comment by golenkovm** [comment]
You're absolutely right! I feel sorry for stealing your time.
- As an admin when switching my role to Student - I can see the Ad hoc debug (off) link
- As an admin when logging as a student using "Login as" mode - I can see the Ad hoc debug (off) link
- When logging natively as a student, using their credentials - the Ad hoc debug (off) link is not displayed.

Everything looks good and seems to be working by design.
Thank you for your help @grabs 

Cheers,
Misha
