### ISSUE TITLE
Better describe the relation to the standard debugusers feature

### ISSUE THREAD

**Issue by mudrd8mz** [grabs/moodle-tool_userdebug#2]
The plugin description at https://moodle.org/plugins/tool_userdebug and the README file should better describe what is the plugin's relation to the standard Moodle's `$CFG->debugusers` feature. E.g. what is different or added (such as the ad-hoc mode, and the ability to control it via the web interface etc).

https://github.com/moodle/moodle/blob/a0fc902eb184cd4097c8ab453ddc57964cd2dbd4/config-dist.php#L725

**Comment by grabs** [comment]
Hi David, thanks again.
I put a better description into the readme.
