### ISSUE TITLE
Please swap default branch in github to be latest stable eg MOODLE_403_STABLE

### ISSUE THREAD

**Issue by brendanheywood** [grabs/moodle-tool_userdebug#3]
When you first visit github you see:

https://github.com/grabs/moodle-tool_userdebug

which defaults to 

https://github.com/grabs/moodle-tool_userdebug/tree/MOODLE_35_STABLE

which makes it look like this plugin is essentially unmaintained when it isn't

**Comment by grabs** [comment]
Thanks, good point :)
The new default branch is MOODLE_403_STABLE

**Comment by brendanheywood** [comment]
thanks heaps :)
