### ISSUE TITLE
Allow temp debugging for logged in as users

### ISSUE THREAD

**Issue by brendanheywood** [grabs/moodle-tool_userdebug#4]
A common use case is when a bug happens for a specific user and we want to reproduce it, but we don't want to inconvenience the user any more or really involve them. We want to be able to login as them, and have debugging on, but NOT have debugging on for the real user when they are logged in. We can't use a capability for this as it will always be leveraging the 'logged in as' user. I think there is 2 ways this could work:

1) you set the debugging as the admin user and then login-as and this is stored in $_SESSION instead of in $SESSION or stored somewhere else so we can still leverage it 
2) we detect the present of $SESSION->realuser and if present we know its going to be an admin user

**Comment by grabs** [comment]
Hi Brendan, thank you for this really cool idea. I now implemented it by using "\core\session\manager::get_realuser()". That makes it possible to start the ad-hoc debugging even if you are logged in with "Log in as".
The new version is online now.

**Comment by brendanheywood** [comment]
thanks @grabs - thats is a fantastic turnaround time :)
