### ISSUE TITLE
Consider removing the debugsettingsopen cookie

### ISSUE THREAD

**Issue by brendanheywood** [grabs/moodle-tool_userdebug#6]
Just about every time someone uses this tool for the first time they get confused about what to do, and then they discover the 'Debug message' toggle with the cog icon.

I would suggest that we completely remove the cookie and toggle logic and always show this. More often that not when you come here you want to see and possibly change the state of it, and it doesn't take up much real estate. The only people using this will be power user admins so showing it all up front is exactly what they need.

**Comment by grabs** [comment]
Hi Brendan, have a look at my answer in #10.
Thank you!
