### ISSUE TITLE
If debug mode is active then warn the user

### ISSUE THREAD

**Issue by brendanheywood** [grabs/moodle-tool_userdebug#8]
We also get a lot of admins who are seeing debugging and freak out thinking that debugging is on in prod, because either they didn't set it up, or they did but then left it and forgot about it. So proposing to add a simple notification when it is on.

**Comment by grabs** [comment]
Hi Brendan, have a look at my answer in #10.
Thank you!

**Comment by brendanheywood** [comment]
@grabs I don't think I can see any of these new features, perhaps you missed a push?

**Comment by brendanheywood** [comment]
thanks this is looking really great
